name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    env:
      CI: true
      COVERAGE: ${{ matrix.node-version == '16.x' && true || false }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn dist
    - run: yarn test

    # Coverage.
    - name: Run coverage
      if: ${{ env.COVERAGE == 'true' }}
      run: |
        yarn coverage
        yarn coverage:report
    - name: Report coverage
      if: ${{ env.COVERAGE == 'true' }}
      uses: codecov/codecov-action@v3
      with:
        files: .nyc_output/coverage.lcov
